---
- name: Step 004.1 - Local host preparation for OpenShift deployment
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  tags:
    - generate_ansible_hosts_file
    - step004
    - step004.1
  tasks:
    - name: generate ansible hosts file for 3.9 and later
      template:
        src: "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/files/hosts_template.{{ osrelease }}.j2"
        dest: "{{ ANSIBLE_REPO_PATH }}/workdir/hosts-{{ env_type }}-{{ guid }}"

    # - name: remove filename parameter from htpasswd authentication for 3.10+
    #   replace:
    #     dest: "{{ ANSIBLE_REPO_PATH }}/workdir/hosts-{{ env_type }}-{{ guid }}"
    #     regexp: ', "filename": "/etc/origin/master/htpasswd"'
    #     replace: ''
    #   when:
    #     - osrelease is version_compare('3.10', '>=')

#########################Configuring openshift-nodes

# - name: Step 004.2 - Node preparation for OpenShift deployment
#   gather_facts: False
#   become: yes
#   hosts:
#     - nodes
#     - infranodes
#     - masters
#   roles:
#     - "{{ ANSIBLE_REPO_PATH }}/roles/host-ocp-node"
#   tags:
#     - openshift_node_tasks
#     - step004
#     - step004.2
#
# - name: Step 004.2.1 - Gluster Node preparation for OpenShift deployment
#   gather_facts: False
#   become: yes
#   hosts:
#     - support
#   vars_files:
#     - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
#   roles:
#     - role: "{{ ANSIBLE_REPO_PATH }}/roles/host-ocp-node"
#       when: install_glusterfs|d(false)|bool
#   tags:
#     - openshift_node_tasks
#     - step004
#     - step004.2.1
#
# ########################Configuring nfs hosts
#
# - name: Step 004.3 - Configuring Nfs Host
#   gather_facts: False
#   become: yes
#   order: sorted
#   hosts:
#     - support
#   vars_files:
#     - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
#   roles:
#     - { role: "{{ ANSIBLE_REPO_PATH }}/roles/host-ocp-nfs", when: 'install_nfs' }
#   tags:
#     - nfs_tasks
#     - step004
#     - step004.3

######################### Run OpenShift Installer

- name: Step 004.4 - Run OpenShift Installer
  gather_facts: False
  become: yes
  hosts:
    - bastions
  tags:
    - install_openshift
    - step004
    - step004.5
  tasks:
  roles:
    - role: "{{ ANSIBLE_REPO_PATH }}/roles/host-ocp-provisioner"
    - role: "{{ ANSIBLE_REPO_PATH }}/roles/host-ocp-installer"

  post_tasks:
    - name: get openshift credentials file
      shell: ansible masters[0] -b -m fetch -a "src=/root/.kube/config dest=/root/.kube/config flat=yes"
      tags:
        - get_openshift_credentials
